### ISSUE TITLE
用wsltty-launcher 启动 manjaro-linux-for-wsl 就闪退

### ISSUE THREAD

**Issue by xBLACKICEx** [riag/wsltty-launcher#2]
安装说明一路过来用wsltty-launcher 启动就闪退 windows版本是18965.10005（2H01）（冲着wsl2来的）
manjaro装的是2019-5-27的
但是bash启动好像没问题, 有谁遇到这问题？ 配置:
mintty_bing_path = ""
mintty_config_dir = ""

[[distro]]
shell="/usr/bin/zsh"
title="manjaro-linux"
icon_name="manjaro.ico"
name = "manjaro-linux"
distro = "manjaro-linux"

**Comment by riag** [comment]
还是建议里使用 windows 10 最新稳定版本的，windows 10 Insider 版本支持 wsl2，对 wsl 可能改动比较大，mintty 可能没那么快就可以支持

**Comment by xBLACKICEx** [comment]
尝鲜代价,我换个渠道搞一下wsl2吸引力大还想这折腾几下实在不行再夹着尾巴回到19h2

**Comment by riag** [comment]
wsl2 是吸引力大，如果你想继续用 wsl2 的话，可以试用下微软最新出的 windows terminal
